import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const paths=['/','/services/','/services/digital-product-passport/','/services/industrial-automation/','/dpp-readiness/','/automation-assessment/','/industries/','/work/','/insights/','/about/','/contact/','/insights/dpp-readiness-questions/','/insights/automation-pilot/','/industries/garments-textiles/','/industries/industrial-manufacturing/','/industries/technology-businesses/','/work/demo-product-data-pilot/','/work/demo-factory-visibility/','/services/data-artificial-intelligence/','/services/renewable-energy-ev/','/services/semiconductor-microelectronics/','/services/drone-robotics/','/approach/service-delivery/','/approach/consulting-process/','/services/digital-product-passport/rmg-bangladesh/','/insights/rmg-product-story/','/insights/factory-signal-story/'];
let errors=[];
for(const width of [360,390,768,1024,1280,1440,1920]){
 const page=await browser.newPage({viewport:{width,height:900},deviceScaleFactor:1});
 page.on('pageerror',e=>errors.push(`JS ${width}: ${e.message}`));
 for(const p of paths){await page.goto('http://127.0.0.1:5173'+p,{waitUntil:'domcontentloaded'});await page.waitForTimeout(220);const x=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:window.innerWidth,title:document.title}));if(x.scroll>x.viewport+2)errors.push(`OVERFLOW ${width} ${p}: ${x.scroll} > ${x.viewport}`);if(!x.title)errors.push(`TITLE ${p}`)}
 await page.goto('http://127.0.0.1:5173/');await page.getByRole('button',{name:'Next slide'}).click();await page.waitForTimeout(850);if(!(await page.locator('.hero h1').innerText()).includes('product'))errors.push(`SLIDER ${width}`);
 if(width<=1390){await page.getByRole('button',{name:'Open menu'}).click();if(!(await page.getByRole('navigation',{name:'Mobile navigation'}).isVisible()))errors.push(`MOBILE MENU ${width}`);await page.getByRole('button',{name:'Close menu'}).click()}else{for(const menu of ['What we do','Work','Insights','About']){await page.getByRole('button',{name:menu,exact:true}).click();if(!(await page.locator('.mega-upgraded').isVisible()))errors.push(`MEGA ${width} ${menu}`);await page.keyboard.press('Escape')}}
 await page.getByRole('button',{name:'Open quick actions'}).click();const selector=page.getByRole('combobox',{name:'Website language'});if(!(await selector.isVisible()))errors.push(`LANG IN DOCK ${width}`);await selector.selectOption('bn');await page.waitForTimeout(100);if(!(await page.locator('h1').innerText()).includes('পণ্য'))errors.push(`BN HOME ${width}`);
 await page.goto('http://127.0.0.1:5173/services/digital-product-passport/');if(!(await page.locator('h1').innerText()).includes('পণ্যের'))errors.push(`BN DPP ${width}`);await page.getByRole('button',{name:'Open quick actions'}).click();for(const [code,needle] of [['fr','données'],['de','Produktdaten'],['es','datos'],['ar','بيانات']]){await page.locator('#site-language').selectOption(code);await page.waitForTimeout(220);if(!(await page.locator('h1').innerText()).includes(needle))errors.push(`TRANSLATION ${code} ${width}`);if(code==='ar'){const x=await page.evaluate(()=>({dir:document.documentElement.dir,scroll:document.documentElement.scrollWidth,viewport:innerWidth}));if(x.dir!=='rtl')errors.push(`AR RTL ${width}`);if(x.scroll>x.viewport+2)errors.push(`AR OVERFLOW ${width}: ${x.scroll}`)}}await page.locator('#site-language').selectOption('en');if(!(await page.locator('h1').innerText()).includes('product'))errors.push(`EN SWITCH ${width}`);
 if(width===390){await page.locator('.dock-whatsapp').waitFor();const wa=await page.locator('.dock-whatsapp').getAttribute('href');if(!wa?.startsWith('https://wa.me/8801711853769'))errors.push('WHATSAPP LINK');await page.locator('.dock-chat').click();if(!(await page.locator('.assistant-panel').isVisible()))errors.push('ASSISTANT OPEN');await page.locator('.assistant-topics button').first().click();if(!(await page.locator('.assistant-answer').isVisible()))errors.push('ASSISTANT ANSWER');await page.getByRole('button',{name:'Close assistant'}).click();await page.goto('http://127.0.0.1:5173/dpp-readiness/');for(const fieldset of await page.locator('.readiness-questions fieldset').all()){await fieldset.getByRole('button',{name:'Yes'}).click()}await page.getByRole('button',{name:'See suggested next steps'}).click();if(!(await page.locator('.readiness-result').isVisible()))errors.push('DPP CHECKLIST')}console.log('checked',width,paths.length,'pages + menus + six languages');await page.close();
}
await browser.close();console.log(errors.length?errors.join('\n'):'PASS: no page errors or horizontal overflow across checked widths');if(errors.length)process.exit(1);
