import viCommon from './draft-locales/vi-common.json';
import kmCommon from './draft-locales/km-common.json';
import siCommon from './draft-locales/si-common.json';
import taCommon from './draft-locales/ta-common.json';
import filCommon from './draft-locales/fil-common.json';
import React,{useEffect,useState} from 'react';
const draftLoaders={bn:()=>import('./draft-locales/bn.json'),fr:()=>import('./draft-locales/fr.json'),de:()=>import('./draft-locales/de.json'),es:()=>import('./draft-locales/es.json'),ar:()=>import('./draft-locales/ar.json'),hi:()=>import('./draft-locales/hi.json'),ur:()=>import('./draft-locales/ur.json'),id:()=>import('./draft-locales/id.json'),vi:()=>import('./draft-locales/vi.json'),km:()=>import('./draft-locales/km.json'),si:()=>import('./draft-locales/si.json'),ta:()=>import('./draft-locales/ta.json'),fil:()=>import('./draft-locales/fil.json')};
const loadedDrafts={};const pendingDrafts={};
function ensureDraft(lang){if(!draftLoaders[lang]||loadedDrafts[lang]||pendingDrafts[lang])return;pendingDrafts[lang]=draftLoaders[lang]().then(mod=>{loadedDrafts[lang]=mod.default;window.dispatchEvent(new Event('deshik-language-change'))}).catch(()=>{}).finally(()=>{delete pendingDrafts[lang]})}
const key='deshik-language';
export const languages=[['en','English'],['bn','বাংলা'],['fr','Français'],['de','Deutsch'],['es','Español'],['ar','العربية'],['hi','हिन्दी'],['ur','اردو'],['id','Bahasa Indonesia'],['vi','Tiếng Việt'],['km','ភាសាខ្មែរ'],['si','සිංහල'],['ta','தமிழ்'],['fil','Filipino']];
export function currentLanguage(){try{const value=localStorage.getItem(key);return languages.some(([code])=>code===value)?value:'en'}catch{return 'en'}}
export function useLanguage(){const[lang,setLang]=useState(currentLanguage),[,refresh]=useState(0);useEffect(()=>{const update=()=>{const next=currentLanguage();document.documentElement.lang=next;document.documentElement.dir=['ar','ur'].includes(next)?'rtl':'ltr';ensureDraft(next);setLang(next);refresh(v=>v+1)};update();window.addEventListener('deshik-language-change',update);window.addEventListener('storage',update);return()=>{window.removeEventListener('deshik-language-change',update);window.removeEventListener('storage',update)}},[]);return lang}
export function localize(english,variants={}){return variants[currentLanguage()]||english}
export function draftT(text,lang=currentLanguage()){if(typeof text!=='string'||lang==='en')return text;const key=text.trim();const translated=loadedDrafts[lang]?.[key];if(!translated)return text;return text.replace(key,translated)}
export function translateDeep(value,lang=currentLanguage()){if(Array.isArray(value))return value.map(item=>translateDeep(item,lang));if(value&&typeof value==='object'&&value.constructor===Object)return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,translateDeep(v,lang)]));return typeof value==='string'?draftT(value,lang):value}
export function languageText(en,bn){return currentLanguage()==='bn'&&bn?bn:draftT(en)}
export function LanguageSwitch(){const lang=useLanguage();function set(value){try{localStorage.setItem(key,value)}catch{}window.dispatchEvent(new Event('deshik-language-change'))}return <div className="language-picker"><label htmlFor="site-language">{common[lang].language}</label><select id="site-language" aria-label={common[lang].language} value={lang} onChange={e=>set(e.target.value)}>{languages.map(([code,name])=><option key={code} value={code} lang={code}>{name}</option>)}</select><p>{common[lang].translationNote}</p></div>}
export const common={
en:{services:'Services',dpp:'DPP Consulting',automation:'Industrial Automation',industries:'Industries',work:'Work',insights:'Insights',about:'About',contact:'Contact',letsTalk:"Let's talk",whatWeDo:'What we do',ourApproach:'Our approach',explore:'Explore our expertise',quick:'QUICK ACTIONS',close:'CLOSE',book:'Book a meeting',readiness:'DPP readiness',review:'Automation review',next:'THE NEXT CONVERSATION',discussion:'Start a conversation',language:'Website language',translationNote:'Translation drafts require human review. Refer to the English version for regulatory details.'},
bn:{services:'সেবাসমূহ',dpp:'ডিপিপি পরামর্শ',automation:'ইন্ডাস্ট্রিয়াল অটোমেশন',industries:'শিল্পখাত',work:'আমাদের কাজ',insights:'ভাবনা',about:'আমাদের সম্পর্কে',contact:'যোগাযোগ',letsTalk:'কথা বলুন',whatWeDo:'আমাদের সেবা',ourApproach:'আমাদের পদ্ধতি',explore:'আমাদের দক্ষতা দেখুন',quick:'দ্রুত যোগাযোগ',close:'বন্ধ করুন',book:'মিটিং নির্ধারণ',readiness:'ডিপিপি প্রস্তুতি',review:'অটোমেশন পর্যালোচনা',next:'পরবর্তী আলোচনা',discussion:'আলোচনা শুরু করুন',language:'ওয়েবসাইটের ভাষা',translationNote:'অনুবাদগুলো খসড়া; বিশেষজ্ঞ পর্যালোচনা প্রয়োজন। নিয়ন্ত্রক তথ্যের জন্য ইংরেজি সংস্করণ দেখুন।'},
fr:{services:'Services',dpp:'Conseil DPP',automation:'Automatisation industrielle',industries:'Secteurs',work:'Nos projets',insights:'Analyses',about:'À propos',contact:'Contact',letsTalk:'Parlons-en',whatWeDo:'Nos expertises',ourApproach:'Notre approche',explore:'Découvrir nos expertises',quick:'ACCÈS RAPIDE',close:'FERMER',book:'Prendre rendez-vous',readiness:'Préparation DPP',review:'Analyse automatisation',next:'PARLONS DE VOTRE PROJET',discussion:'Prendre contact',language:'Langue du site',translationNote:'Traductions provisoires à valider. Consultez la version anglaise pour les détails réglementaires.'},
de:{services:'Leistungen',dpp:'DPP-Beratung',automation:'Industrieautomation',industries:'Branchen',work:'Unsere Arbeit',insights:'Einblicke',about:'Über uns',contact:'Kontakt',letsTalk:'Kontakt aufnehmen',whatWeDo:'Unsere Leistungen',ourApproach:'Unser Ansatz',explore:'Leistungen entdecken',quick:'SCHNELLZUGRIFF',close:'SCHLIESSEN',book:'Termin vereinbaren',readiness:'DPP-Bereitschaft',review:'Automationsprüfung',next:'LASSEN SIE UNS SPRECHEN',discussion:'Gespräch beginnen',language:'Website-Sprache',translationNote:'Übersetzungsentwürfe müssen geprüft werden. Für regulatorische Details gilt die englische Fassung.'},
es:{services:'Servicios',dpp:'Consultoría DPP',automation:'Automatización industrial',industries:'Sectores',work:'Nuestro trabajo',insights:'Perspectivas',about:'Nosotros',contact:'Contacto',letsTalk:'Hablemos',whatWeDo:'Qué hacemos',ourApproach:'Nuestro enfoque',explore:'Explorar servicios',quick:'ACCESOS RÁPIDOS',close:'CERRAR',book:'Reservar una reunión',readiness:'Preparación DPP',review:'Revisión de automatización',next:'HABLEMOS DE SU PROYECTO',discussion:'Iniciar conversación',language:'Idioma del sitio',translationNote:'Las traducciones son borradores pendientes de revisión. Consulte el inglés para detalles normativos.'},
ar:{services:'الخدمات',dpp:'استشارات جواز المنتج الرقمي',automation:'الأتمتة الصناعية',industries:'القطاعات',work:'أعمالنا',insights:'رؤى',about:'من نحن',contact:'اتصل بنا',letsTalk:'لنتحدث',whatWeDo:'ما نقدمه',ourApproach:'منهجنا',explore:'استكشف خدماتنا',quick:'إجراءات سريعة',close:'إغلاق',book:'احجز موعداً',readiness:'جاهزية جواز المنتج',review:'مراجعة الأتمتة',next:'لنبدأ الحديث',discussion:'ابدأ المحادثة',language:'لغة الموقع',translationNote:'الترجمات مسودات تحتاج إلى مراجعة. يُرجى الرجوع إلى النسخة الإنجليزية للتفاصيل التنظيمية.'},
hi:{services:'सेवाएँ',dpp:'डीपीपी परामर्श',automation:'औद्योगिक स्वचालन',industries:'उद्योग',work:'हमारा कार्य',insights:'अंतर्दृष्टि',about:'हमारे बारे में',contact:'संपर्क',letsTalk:'बात करें',whatWeDo:'हम क्या करते हैं',ourApproach:'हमारा दृष्टिकोण',explore:'विशेषज्ञता देखें',quick:'त्वरित विकल्प',close:'बंद करें',book:'बैठक तय करें',readiness:'डीपीपी तैयारी',review:'स्वचालन समीक्षा',next:'अगली बातचीत',discussion:'बातचीत शुरू करें',language:'वेबसाइट की भाषा',translationNote:'अनुवाद प्रारूप हैं और मानवीय समीक्षा आवश्यक है। नियामकीय विवरण के लिए अंग्रेज़ी संस्करण देखें।'},
ur:{services:'خدمات',dpp:'ڈی پی پی مشاورت',automation:'صنعتی خودکار نظام',industries:'صنعتیں',work:'ہمارا کام',insights:'تجزیے',about:'ہمارے بارے میں',contact:'رابطہ',letsTalk:'بات کریں',whatWeDo:'ہم کیا کرتے ہیں',ourApproach:'ہمارا طریقہ',explore:'مہارت دیکھیں',quick:'فوری اختیارات',close:'بند کریں',book:'ملاقات طے کریں',readiness:'ڈی پی پی تیاری',review:'آٹومیشن جائزہ',next:'اگلی گفتگو',discussion:'گفتگو شروع کریں',language:'ویب سائٹ کی زبان',translationNote:'یہ تراجم مسودے ہیں اور انسانی نظرثانی ضروری ہے۔ ضابطہ جاتی تفصیلات کے لیے انگریزی نسخہ دیکھیں۔'},
id:{services:'Layanan',dpp:'Konsultasi DPP',automation:'Otomasi Industri',industries:'Industri',work:'Pekerjaan Kami',insights:'Wawasan',about:'Tentang Kami',contact:'Kontak',letsTalk:'Mari bicara',whatWeDo:'Keahlian Kami',ourApproach:'Pendekatan Kami',explore:'Jelajahi keahlian',quick:'AKSI CEPAT',close:'TUTUP',book:'Jadwalkan pertemuan',readiness:'Kesiapan DPP',review:'Tinjauan otomasi',next:'PERCAKAPAN BERIKUTNYA',discussion:'Mulai percakapan',language:'Bahasa situs',translationNote:'Terjemahan ini masih draf dan memerlukan tinjauan manusia. Lihat versi bahasa Inggris untuk rincian peraturan.'},
vi:viCommon,km:kmCommon,si:siCommon,ta:taCommon,fil:filCommon
};
