import React, { useState } from 'react';
import { ArrowUpRight, Check, Compass, Leaf, Cpu, Truck, Sprout } from 'lucide-react';
import { draftT, translateDeep, useLanguage } from './i18n.jsx';
import './industry-playbooks.css';

export const playbooks = {
  '/industries/energy-ev/': {
    number: '04', label: 'ENERGY & ELECTRIC MOBILITY', title: 'Build the pathway before the infrastructure.', lead: 'Energy transition and electric mobility bring together commercial decisions, physical assets, data and people. A useful first step is to define the operating question and the partners required to answer it.', icon: Leaf, color: 'lime',
    context: 'The opportunity is rarely one device or one installation. Site conditions, demand, energy availability, operations and support responsibilities affect what can be delivered.',
    lenses: [
      { title: 'Opportunity & demand', question: 'Who needs the service, where, and at what usage pattern?', detail: 'Map customers, locations, energy demand and the alternatives people currently use. Record assumptions separately from observed usage, then identify the smallest evidence-gathering pilot.', artifact: 'Demand hypothesis and stakeholder map' },
      { title: 'Infrastructure & partners', question: 'What must work around the asset?', detail: 'Explore site ownership, power availability, equipment interfaces, operating partners, maintenance and permissions with qualified specialists. Do not treat a conceptual map as an engineering approval.', artifact: 'Dependency and responsibility map' },
      { title: 'Delivery & learning', question: 'How will a pilot become a reliable service?', detail: 'Define availability, support, safety responsibilities, user experience and data needs before scaling. Agree the conditions under which a pilot should expand, change or stop.', artifact: 'Pilot scope and decision gates' },
    ],
    steps: [['Frame', 'Name the customer and operating decision.'], ['Validate', 'Check demand, site assumptions and partner roles.'], ['Pilot', 'Choose a limited use case with measurable learning.'], ['Review', 'Decide on investment, ownership and support.']],
    faqs: [['Is Deshik installing EV chargers or energy assets?', 'This page describes an exploratory consulting pathway, not a claim of installation, engineering certification or a delivered infrastructure project. Any technical work would require defined scope and suitably qualified partners.'], ['Can a market assessment replace a site study?', 'No. Commercial feasibility and technical site suitability are different questions. Both need appropriate evidence and specialist review before commitments are made.'], ['What makes a useful first pilot?', 'One that tests a real customer need, operating responsibilities, site constraints and a measurable scale-or-stop decision rather than only demonstrating equipment.']],
    related: [['Explore Renewable Energy & EV', '/services/renewable-energy-ev/'], ['Read the AI data-readiness guide', '/insights/ai-ready-data/']], note: 'Exploratory sector perspective. No installed assets, permits, engineering designs or verified Deshik project outcomes are implied.'
  },
  '/industries/electronics-semiconductors/': {
    number: '05', label: 'ELECTRONICS & SEMICONDUCTORS', title: 'Find your place in a complex value chain.', lead: 'From design and testing to packaging, equipment support and partnerships, electronics value chains contain distinct opportunities. The work begins by identifying a credible role—not assuming every entrant needs a fabrication plant.', icon: Cpu, color: 'violet',
    context: 'A realistic opportunity depends on customer demand, technical qualifications, people, suppliers and a route to market. Ambition should be separated from verified operating capability.',
    lenses: [
      { title: 'Value-chain position', question: 'Which precise activity is under consideration?', detail: 'Distinguish design services, verification, testing, assembly, packaging, equipment support and adjacent software. Describe the output and customer for one activity before broadening the ambition.', artifact: 'Value-chain opportunity map' },
      { title: 'Capability & evidence', question: 'What skills and qualifications are already present?', detail: 'Inventory talent, facilities, partners, quality systems and validated experience. Mark every dependency that would require a partner or additional investment; avoid presenting prospective capacity as existing capacity.', artifact: 'Capability and gap register' },
      { title: 'Commercial pathway', question: 'What would justify the next investment?', detail: 'Test potential demand and qualification requirements with relevant buyers and partners. Establish a learning milestone and a decision gate before committing to specialized facilities or equipment.', artifact: 'Partner and milestone roadmap' },
    ],
    steps: [['Scope', 'Define the value-chain layer and customer problem.'], ['Map', 'Identify skills, qualification and partner gaps.'], ['Test', 'Validate demand and a limited collaboration.'], ['Decide', 'Set a credible next investment milestone.']],
    faqs: [['Does this mean Deshik operates a semiconductor facility?', 'No. This is a strategy and ecosystem-development perspective, not a claim of semiconductor manufacturing, certification or completed client delivery.'], ['Where can a smaller organization begin?', 'The starting point depends on verified skills and customer demand. A focused design, test, software or partnership question can be explored without assuming a full fabrication facility.'], ['What is the most important early evidence?', 'A specific customer requirement, a realistic capability assessment and the qualification or partner pathway needed to serve that requirement.']],
    related: [['Explore Semiconductor & Microelectronics', '/services/semiconductor-microelectronics/'], ['Read the value-chain field guide', '/insights/semiconductor-value-chain/']], note: 'Exploratory sector perspective. Facility ownership, production capability and completed semiconductor engagements are not claimed.'
  },
  '/industries/transport-logistics/': {
    number: '06', label: 'TRANSPORT & LOGISTICS', title: 'Make every handoff easier to see.', lead: 'Goods move through people, locations, systems and documents. Better decisions depend on knowing where information is captured, where it is delayed and who can act on an exception.', icon: Truck, color: 'lime',
    context: 'A tracking screen alone does not fix an uncertain handoff. Start with a shipment or order journey, the evidence exchanged at each stage and the exception a team struggles to resolve.',
    lenses: [
      { title: 'Handoff visibility', question: 'Where does the status become uncertain?', detail: 'Follow one representative shipment from origin through receipt. Compare what operations, customer service and external partners believe has happened. Mark manual re-entry and gaps in identifiers.', artifact: 'Shipment handoff and source map' },
      { title: 'Exception response', question: 'Who acts when the plan changes?', detail: 'Identify recurring delays, missing documents or unclear ownership. Agree which exception matters, the evidence required to recognize it and the person authorized to respond.', artifact: 'Exception-to-action workflow' },
      { title: 'Pilot measurement', question: 'What improvement would the team notice?', detail: 'Define baseline time to locate a shipment, reconcile a document or resolve an exception. Test a limited route or workflow before selecting an integration at network scale.', artifact: 'Pilot metrics and integration questions' },
    ],
    steps: [['Observe', 'Follow a real handoff and its documents.'], ['Align', 'Agree identifiers, owners and response rules.'], ['Pilot', 'Test a limited route or exception workflow.'], ['Extend', 'Review impact before wider integration.']],
    faqs: [['Do we need to replace our tracking system?', 'Not necessarily. First determine where existing records, partner messages and responsibilities break down. Integration or process improvement may be more relevant than a new platform.'], ['What is a useful early metric?', 'For example, time to identify and resolve a defined exception, measured against the current workflow. The metric should reflect a real decision rather than simply more data on a dashboard.'], ['Is this a claim of fleet or logistics operations by Deshik?', 'No. This page frames potential consulting questions and does not imply ownership of vehicles, freight services or a completed client project.']],
    related: [['Explore Digital Transformation', '/services/digital-transformation/'], ['Read the factory signal field guide', '/insights/industrial-data-to-decision/']], note: 'Exploratory sector perspective. Carrier services, fleet ownership and verified project outcomes are not implied.'
  },
  '/industries/agriculture-food/': {
    number: '07', label: 'AGRICULTURE & FOOD SYSTEMS', title: 'Connect the field to a better decision.', lead: 'Agriculture and food supply chains depend on context: production conditions, collection points, quality information and the people making decisions. Technology works best when it answers a specific operational need.', icon: Sprout, color: 'violet',
    context: 'Start with a real information gap—such as inconsistent lot records, delayed quality feedback or uncertain storage conditions—rather than assuming a sensor or app is the solution.',
    lenses: [
      { title: 'Origin & identity', question: 'Can the team link the right information to the right lot?', detail: 'Map how products are identified at collection, processing and distribution. Note the people who create and correct each record, and where identifiers are lost during aggregation.', artifact: 'Lot identity and handoff map' },
      { title: 'Quality & conditions', question: 'Which conditions actually change a decision?', detail: 'Identify what the team measures today and what action follows an exception. Consult qualified food-safety and agronomy specialists where technical interpretation or regulated claims are involved.', artifact: 'Decision and evidence register' },
      { title: 'Adoption & access', question: 'Will the workflow work for the people using it?', detail: 'Consider connectivity, language, training, device availability and data entry time. Pilot a small process with the people responsible for maintaining it, then revise before wider rollout.', artifact: 'Adoption-aware pilot plan' },
    ],
    steps: [['Listen', 'Select one producer or supply-chain question.'], ['Trace', 'Map identity, evidence and current handoffs.'], ['Trial', 'Test a manageable data or workflow change.'], ['Adapt', 'Review user effort, reliability and value.']],
    faqs: [['Does this page promise a traceability platform?', 'No. It outlines possible discovery and pilot work; any software, integration or sector-specific delivery would require a defined scope and verified expertise.'], ['What should a first pilot cover?', 'A single product flow, lot or recurring quality question with clear ownership and a measurable baseline, rather than an entire supply chain at once.'], ['Can this guidance establish food-safety compliance?', 'No. Safety and regulatory obligations require qualified specialists and applicable local rules. This is only an operational planning perspective.']],
    related: [['Explore Operations & Performance', '/services/operations-performance/'], ['Read the DPP product-record explainer', '/insights/dpp-data-architecture/']], note: 'Exploratory sector perspective. No agricultural operations, certification or verified client results are claimed.'
  },
};

export function IndustryPlaybook({ data: source, Shell, CTA }) {
  const lang = useLanguage();
  const data = translateDeep(source, lang);
  const [active, setActive] = useState(0);
  const Icon = source.icon;
  const chosen = data.lenses[active];
  return <Shell><section className={'playbook-hero playbook-' + source.color}><div><span className="eyebrow">{draftT('DESHIK / INDUSTRY PLAYBOOK')} {source.number}</span><h1>{data.title}</h1><p>{data.lead}</p><a href="#playbook-lenses" className="button-primary">{draftT('Explore the decisions')} <ArrowUpRight size={18}/></a></div><div className="playbook-hero-art" aria-hidden="true"><span className="playbook-orbit orbit-one"/><span className="playbook-orbit orbit-two"/><Icon size={92} strokeWidth={.8}/><span className="playbook-coordinate">{source.number} / DESHIK</span></div></section><section className="playbook-context"><div><span className="eyebrow dark">{draftT('THE CONTEXT')}</span><h2>{data.label}</h2></div><p>{data.context}</p></section><section className="playbook-lenses" id="playbook-lenses"><div className="playbook-heading"><span className="eyebrow dark">{draftT('01 / DECISION LENSES')}</span><h2>{draftT('Three questions. A sharper place to begin.')}</h2><p>{draftT('Select a lens to see a potential first conversation and a tangible working output.')}</p></div><div className="playbook-lens-buttons" role="group" aria-label={draftT('Select a decision lens')}>{data.lenses.map((lens,i)=><button type="button" key={lens.title} aria-pressed={active===i} onClick={()=>setActive(i)}><span>0{i+1}</span><strong>{lens.title}</strong><ArrowUpRight size={19}/></button>)}</div><div className="playbook-lens-detail" aria-live="polite"><div><span className="eyebrow dark">{draftT('QUESTION TO EXPLORE')}</span><h3>{chosen.question}</h3></div><div><p>{chosen.detail}</p><span className="playbook-artifact"><Check size={17}/>{draftT('Possible output')}: {chosen.artifact}</span></div></div></section><section className="playbook-path"><div><span className="eyebrow dark">{draftT('02 / A PRACTICAL PATH')}</span><h2>{draftT('How an exploration could unfold.')}</h2></div><div className="playbook-path-grid">{data.steps.map(([name,detail],i)=><article key={name}><span>0{i+1}</span><h3>{name}</h3><p>{detail}</p></article>)}</div></section><section className="playbook-faq"><div><span className="eyebrow dark">{draftT('03 / QUESTIONS & BOUNDARIES')}</span><h2>{draftT('What this page does—and does not—mean.')}</h2><p>{data.note}</p></div><div>{data.faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section><section className="playbook-related"><div><span className="eyebrow dark">{draftT('EXPLORE NEXT')}</span><h2>{draftT('Connect this context to an idea.')}</h2></div>{data.related.map(([label,url])=><a key={url} href={url}>{label}<ArrowUpRight size={19}/></a>)}</section><CTA title="Where could you start?" sub="Tell us the question behind your next decision. We can explore whether a scoped conversation makes sense." /></Shell>;
}

export function IndustryPlaybookGrid() {const lang=useLanguage();return <section className="industry-playbook-directory"><div><span className="eyebrow dark">{draftT('INDUSTRY PLAYBOOKS / 04—07')}</span><h2>{draftT('More contexts. Better questions.')}</h2><p>{draftT('Explore four additional sector lenses. Each begins with a decision to clarify, not a claim of delivered projects.')}</p></div><div>{Object.entries(playbooks).map(([url,source])=>{const Icon=source.icon;return <a href={url} key={url}><span>{source.number} / {draftT(source.label,lang)}</span><Icon size={24}/><strong>{draftT(source.title,lang)}</strong><ArrowUpRight size={18}/></a>})}</div></section>}
