// Menu & Footer.pdf supplies the taxonomy. Links point to real page sections; topic lists are editorial scope, not claims of delivered projects.
export const megaMenus={
services:{eyebrow:'WHAT WE DO',title:'Capabilities for a changing world.',description:'Explore our core consulting offer, cooperation models and emerging areas of interest.',groups:[{title:'Featured solutions',links:[['Find your starting point','/services/#find-your-path'],['Resource Center & worksheets','/resources/'],['Trusted Data Gateway (TDG)','/services/trusted-data-gateway/'],['Digital Product Passport','/services/digital-product-passport/'],['Interactive DPP product journey','/experience/dpp-product-journey/'],['Industrial Automation','/services/industrial-automation/'],['Factory Operations Studio','/experience/factory-operations-studio/'],['All capabilities','/services/#capabilities']]},{title:'Business capabilities',links:[['Strategy & Growth','/services/strategy-growth/'],['Digital & Technology Transformation','/services/digital-transformation/'],['Operations & Performance','/services/operations-performance/'],['Business Cooperation','/services/#business-cooperation']]},{title:'Explore further',links:[['Consulting Services','/services/#consulting-services'],['Data & Artificial Intelligence','/services/data-artificial-intelligence/'],['Renewable Energy & EV','/services/renewable-energy-ev/'],['Semiconductor & Microelectronics','/services/semiconductor-microelectronics/'],['Drone & Robotics','/services/drone-robotics/']]}]},
about:{eyebrow:'WHO WE ARE',title:'Get to know Deshik.',description:'Explore our story, people, direction and the way we collaborate.',groups:[{title:'About Deshik',links:[['Who we are','/about/who-we-are/'],['Our perspective','/about/#brand-perspective'],['Our Leadership','/about/leadership/'],['Our Mission','/about/mission/'],['Our Vision & Goals','/about/vision/']]},{title:'Leadership profiles',links:[['Belal Ahmed — CEO','/about/leadership/belal-ahmed/'],['Nizam Farid Ahmed — Principal Consultant','/about/leadership/nizam-farid-ahmed/'],['Nahid Mustafa — COO','/about/leadership/nahid-mustafa/'],['Alamgir Kabir Roni — CTO','/about/leadership/alamgir-kabir-roni/']]},{title:'Connect with us',links:[['Partners & Affiliations','/about/partners-affiliations/'],['Careers & Culture','/about/careers-culture/'],['Work as a Consultant','/about/work-as-consultant/'],['Our Consultants','/about/consultants/'],['Locations & Contact','/contact/']]}]},
work:{eyebrow:'HOW WE WORK',title:'From challenge to action.',description:'See the types of work we explore, how engagements are structured and what proof will be published.',groups:[{title:'Our approach',links:[['Our Consulting Process','/approach/consulting-process/'],['Our Service Delivery Process','/approach/service-delivery/'],['Case studies & proof','/work/#case-studies'],['Discuss a project','/contact/']]},{title:'Business cooperation',links:[['Joint Ventures & Alliances','/work/#business-cooperation'],['International Market Expansion','/work/#business-cooperation'],['Strategic Partnerships','/work/#business-cooperation']]},{title:'Consulting work',links:[['Business Operations & HR','/work/#consulting-services'],['Marketing & PR','/work/#consulting-services'],['IT & Automation','/work/#consulting-services']]}]},
insights:{eyebrow:'PERSPECTIVES',title:'Ideas worth exploring.',description:'Practical guides and topic areas drawn from Deshik’s industry, service and technology interests.',groups:[{title:'Published guides',links:[['DPP readiness questions','/insights/dpp-readiness-questions/'],['Fictional product record demo','/experience/dpp-product-journey/'],['DPP product record architecture','/insights/dpp-data-architecture/'],['Garment data handoffs','/insights/garment-data-handoffs/'],['Choosing an automation pilot','/insights/automation-pilot/'],['Fictional factory studio','/experience/factory-operations-studio/'],['All field guides','/insights/#field-guides'],['Product-data map','/resources/dpp-data-map/'],['Automation pilot canvas','/resources/automation-pilot-canvas/'],['RMG product-data story','/insights/rmg-product-story/'],['Factory signal story','/insights/factory-signal-story/']]},{title:'Browse by perspective',links:[['Industry Insights','/insights/#industry-insights'],['Services Insights','/insights/#services-insights'],['Technology Insights','/insights/#technology-insights']]},{title:'More from Deshik',links:[['Hot Topics','/insights/#hot-topics'],['News & Events','/insights/#news-events'],['About the team','/about/']]}]},
industries:{eyebrow:'INDUSTRIES',title:'Context matters.',description:'Explore sector interests across technology, enterprise and the public sphere.',groups:[{title:'Industry groups',links:[['Tech','/industries/#tech'],['Enterprises','/industries/#enterprises'],['Social & Public','/industries/#social-public']]},{title:'Priority conversations',links:[['Energy & EV','/industries/energy-ev/'],['Electronics & Semiconductors','/industries/electronics-semiconductors/'],['Transport & Logistics','/industries/transport-logistics/'],['Agriculture & Food','/industries/agriculture-food/'],['Industrial Manufacturing','/industries/industrial-manufacturing/'],['Garments & Textiles','/industries/garments-textiles/'],['Technology Businesses','/industries/technology-businesses/']]},{title:'Solutions',links:[['Industrial Automation','/services/industrial-automation/'],['Trusted Data Gateway (TDG)','/services/trusted-data-gateway/'],['Digital Product Passport','/services/digital-product-passport/'],['Bangladesh RMG & DPP','/services/digital-product-passport/rmg-bangladesh/']]}]}
};
export const topicSections={
'/services/':[
{id:'capabilities',title:'Capabilities',intro:'Core consulting capabilities presented as focused service pages.',topics:['Strategy & Growth Consulting','Operations & Performance Improvement','Digital & Technology Transformation','Financial Advisory','Government Affairs','International Market Expansion'],note:'Financial and government-related engagements are scoped and validated individually.'},
{id:'business-cooperation',title:'Business Cooperation',intro:'Collaboration models that may support growth and market access.',topics:['Joint Ventures & Alliances','Mergers and Acquisitions','Venture Funding','Startup Grooming','Strategic Partnerships','Co-marketing & Co-branding'],note:'Specific delivery responsibilities and regulated advice require confirmation.'},
{id:'next-big-thing',title:'Next Big Thing',intro:'Emerging topics tracked for future opportunity and specialist partnerships.',topics:['Big Data Analytics','Artificial Intelligence','Semiconductor & Microelectronics','Renewable Energy & EV','Drone & Robotics','Fintech & Digital Economy','Media & Satellite Communication'],note:'Areas of interest are not a claim that all specialist services are currently available.'},
{id:'consulting-services',title:'Consulting Services',intro:'Business, marketing and technology work can be scoped as a tailored engagement.',topics:['Business Operations & HR','B2B / B2C Matchmaking','Business Transformation','Project Management','Marketing & PR','IT & Automation','Systems Integration','ERP / CRM','Cybersecurity'],note:'Ask us about verified capabilities and partner-led delivery.'}],
'/about/':[
{id:'who-we-are',title:'Who we are',intro:'Deshik Consulting is a Dhaka-based consultancy bringing together business, technology and execution perspectives.',topics:['Locally grounded thinking','Collaborative delivery','Practical next steps'],note:'The corporate profile describes Deshik as established in 2017; the incorporation date awaits approval for publication.'},
{id:'leadership',title:'Our Leadership',intro:'People behind the work.',topics:['Belal Ahmed — CEO','Nizam Farid Ahmed — Principal Consultant','Nahid Mustafa — COO','Alamgir Kabir Roni — CTO'],note:'Roles reflect the latest website request and require confirmation. The older supplied profile lists Nahid Mustafa as Senior Project Manager; biographies and portraits were not supplied.'},
{id:'mission',title:'Our Mission',intro:'Help organizations navigate change with useful insight, technology and practical implementation.',topics:['Client-focused collaboration','Responsible innovation','Measurable progress'],note:'Draft interpretation of the corporate profile; leadership sign-off required.'},
{id:'vision',title:'Our Vision & Goals',intro:'Build long-term partnerships and support meaningful business progress beyond borders.',topics:['Trust and transparency','Adaptable capabilities','Thoughtful growth'],note:'Draft interpretation of the corporate profile; leadership sign-off required.'},
{id:'partners',title:'Partners & Affiliations',intro:'Partnerships can expand what specialist teams can deliver together.',topics:['Technology partners','Industry networks','Academic collaboration'],note:'Partner names will appear only after scope and permission are verified.'},
{id:'careers',title:'Careers & Culture',intro:'Interested in consulting, technology work or internships? Contact us to learn about current opportunities.',topics:['Consulting','Work Culture','Internships','Job search'],note:'No open role is implied; current vacancies will be published only when approved.'}],
'/work/':[
{id:'approach',title:'How engagements work',intro:'Understand the challenge, map the constraints, agree the scope, then pilot and review with the client team.',topics:['Discovery','Solution design','Pilot and delivery','Handover and improvement'],note:'The exact engagement model depends on the project.'},
{id:'case-studies',title:'Case studies & proof',intro:'We are preparing permissioned project stories that show the brief, Deshik’s role and documented outcomes.',topics:['Challenge and context','What was delivered','What can be evidenced'],note:'No client result or anonymous performance figure is published without documentation and approval.'},
{id:'business-cooperation',title:'Business Cooperation',intro:'The corporate profile describes support across market expansion, alliances and international deal execution.',topics:['Joint Ventures & Alliances','International Market Expansion','Strategic Partnerships','B2B Matchmaking'],note:'Specific commercial or advisory services must be scoped and verified.'},
{id:'consulting-services',title:'Consulting Services',intro:'Potential engagement areas connect business, brand, digital and operations work.',topics:['Business Operations & HR','Marketing & PR','IT & Automation','Project Management'],note:'Services shown here reflect profile categories, not a promise of every technical implementation.'}],
'/insights/':[
{id:'industry-insights',title:'Industry Insights',intro:'Perspectives across sectors in which Deshik follows change.',topics:['Aerospace, Defense & Security','Engineering & Hi-tech','Education','Digitech & Hardware','Agriculture','EV, Automotive & Assembly','Network & Telecommunications','Semiconductors & Electronics','Healthcare'],note:'Topic directory; articles will be added after author and reviewer approval.'},
{id:'services-insights',title:'Services Insights',intro:'Questions at the intersection of business services and digital delivery.',topics:['IT Services','E-Commerce','Software & Platforms','Digital Marketing','IT Outsourcing','BPO'],note:'Topic directory; not every topic currently has a published article.'},
{id:'technology-insights',title:'Technology Insights',intro:'Ideas around data, connectivity and security.',topics:['IoT','Blockchain','Cloud','Cybersecurity','Data and Decision Intelligence'],note:'Topics do not imply specialist project proof.'},
{id:'hot-topics',title:'Hot Topics',intro:'Emerging subjects to watch as technology and markets evolve.',topics:['Big Data Analytics','Artificial Intelligence','Semiconductor & Microelectronics','Renewable Energy & EV','Drone & Robotics','Fintech & Digital Economy','Media & Satellite Communication'],note:'Editorial topics are not claims of established services.'},
{id:'news-events',title:'News & Events',intro:'Company news, events, media appearances, blogs and press releases will live here after editorial approval.',topics:['News','Upcoming Events','Media','Blogs','Press Releases'],note:'No upcoming event or press release is claimed at present.'}],
'/industries/':[
{id:'tech',title:'Tech',intro:'Digital and engineering-led businesses navigating connected markets.',topics:['Aerospace, Defense & Security','Engineering & Hi-tech','Software & Platforms','Digitech & Hardware','IT Services','EV, Automotive & Assembly','Network & Telecommunications','Semiconductors & Electronics','E-Commerce'],note:'Sectors shown are from the supplied taxonomy; verify relevant client proof before claiming sector specialization.'},
{id:'enterprises',title:'Enterprises',intro:'Industrial and service businesses balancing growth, operations and technology.',topics:['Financial Services','Banks & Insurance','Healthcare','Real Estate & Construction','Energy & Power','Garments','FMCG','Retail & Packaging','Industrial Manufacturing'],note:'Explore relevant solutions; sector delivery scope is assessed case by case.'},
{id:'social-public',title:'Social & Public',intro:'Organizations supporting communities, public services and regional development.',topics:['Education','Agriculture','Travel & Tourism','E-Government & Public Sector','Restaurants & Hotels','Transport & Logistics','Media & Entertainment'],note:'Sector labels are exploratory until engagements are documented.'}]
};
